#!/usr/bin/env bash

# Based on "appify" script by Thomas Aylott
# https://mathiasbynens.be/notes/shell-script-mac-apps

APPNAME=${2:-$(basename "$1" ".sh")}
DIR="$APPNAME.app/Contents/MacOS"

if [ -a "$APPNAME.app" ]; then
  echo "$PWD/$APPNAME.app already exists :("
  exit 1
fi

mkdir -p "$DIR"
cp "$1" "$DIR/$APPNAME"
chmod +x "$DIR/$APPNAME"

# Additions for Giphy Messages

RESOURCES_DIR="$APPNAME.app/Contents/Resources"
mkdir -p "$RESOURCES_DIR"
cp "Giphy.applescript" "$RESOURCES_DIR"
cp "send_message.applescript" "$RESOURCES_DIR"
cp "giphy.py" "$RESOURCES_DIR"

echo "$PWD/$APPNAME.app"